services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Stsbl\SendMailAsGroupBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Resources,Tests}'

    Stsbl\SendMailAsGroupBundle\Controller\:
        public: true
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']
        